# 每一页上应该有多少玩家
page-size: 10

# 排行榜更新间隔(单位为秒)(不小于30)
update-interval: 60

# 黑名单玩家
blacklist:
  - "whhhh"

# 排除玩家名正则表达式
exclude-regex: "-"

# 更新不在线玩家的概率
# 取值: 0-1 (0禁止不在线玩家更新, 1始终更新所有玩家)
# 值越高则不在线玩家更新概率越大, 占用更高
# 值越小则不在线玩家更新概率越小, 占用更小
update-offline-chance: 0.5

# 开启正版/离线UUID过滤
# 开启后正版服将不会显示离线登陆的玩家
# 离线服将不会显示正版登录的玩家
# 如果你的服务器遇到排行榜玩家重复的问题(开关过正版验证, 或者vc等代理配置问题)
# 开启这个选项可能修复
uuid-filter: false

# 是否在后台输出调试信息
debug-output: false

# 自定义UI部分
ui:
  header: "<bold>================ <hover:show_text:'<yellow>更新时间: <#FFA500>{updateTime}</#FFA500></yellow>'>{listName} ================</bold>"
  footer: "<aqua>{prevButton}当前: (<white>{currentIndex}</white>/<white>{totalIndex}</white>){nextButton}</aqua>"
  prev-button: "<hover:show_text:'上一页'><dark_aqua> <- </dark_aqua></hover>"
  next-button: "<hover:show_text:'下一页'><dark_aqua> -> </dark_aqua></hover>"
  item: "<gray>⬡</gray> <white>{num}. <green>{playerName}</green> <grey>-</grey> <dark_green>{count}</dark_green></white>"
  current-item: "<light_purple>⬡</light_purple> <yellow>{num}. <green>{playerName}</green> <grey>-</grey> <dark_green>{count}</dark_green></yellow>"

# 排行榜部分
lists:
  # 财富榜示例 (需要Vault和经济插件)
  财富榜:
    color: "#E1A124"
    type: VAULT_BALANCE # 特殊类型
    formatter: "%.2f 元" # 显示两位小数，并加上单位“元”

  挖掘总榜:
    color: "#FFA500"
    type: MINE_BLOCK
    material: [solid]
    expression: "count / 64"
    formatter: "%.1f 组"

  总榜:
    color: "#FB156B"
    type: "%ptl_player_rank_sum_挖掘总榜_放置榜_挖矿榜_跑图榜_击杀总榜_击杀玩家榜_死亡榜_钓鱼榜_附魔榜_合成榜_交易榜_在线时间_财富榜%"
    reversed: true
    formatter: "%.0f 排名和"

  放置榜:
    color: "#A52A2A"
    type: USE_ITEM
    material: [ blocks ]
    expression: "count / 64"
    formatter: "%.1f 组"

  挖矿榜:
    color: "#FFD700"
    type: MINE_BLOCK
    material: [ coal_ores, copper_ores, diamond_ores, emerald_ores, gold_ores, lapis_ores, redstone_ores, NETHER_QUARTZ_ORE, ANCIENT_DEBRIS ]
    expression: "count / 64"
    formatter: "%.1f 组"

  跑图榜:
    color: "#00FF00"
    type: "%ptl_player_count_sum_走路榜_跑步榜_飞行榜%"
    expression: "count / 100 / 1000"
    formatter: "%.1f 公里"

  击杀总榜:
    color: "#FF00FF"
    type: MOB_KILLS

  击杀玩家榜:
    color: "#FF0022"
    type: PLAYER_KILLS

  死亡榜:
    color: "#8B0000"
    type: DEATHS

  钓鱼榜:
    color: "#0000FF"
    type: FISH_CAUGHT

  附魔榜:
    color: "#ADD8E6"
    type: ITEM_ENCHANTED

  合成榜:
    color: "#FFA500"
    type: CRAFT_ITEM
    material: [ all ]
    expression: "count / 64"
    formatter: "%.1f 组"

  交易榜:
    color: "#31FFB1"
    type: TRADED_WITH_VILLAGER

  在线时间:
    color: "#FF00FF"
    type: PLAY_ONE_MINUTE
    expression: "count / 20 / 60 / 60"
    formatter: "%.1f 小时"

  # 下面这些是作为跑图榜的计算来源
  走路榜:
    hidden: true
    type: WALK_ONE_CM

  跑步榜:
    hidden: true
    type: SPRINT_ONE_CM

  飞行榜:
    hidden: true
    type: AVIATE_ONE_CM
