page-size: 10
update-interval: 60

ui:
  header: "<aqua>================ <hover:show_text:'<yellow>更新时间: <#FFA500>{updateTime}</#FFA500></yellow>'>{listName} ================</aqua>"
  footer: "<aqua>{prevButton}当前: (<white>{currentIndex}</white>/<white>{totalIndex}</white>){nextButton}</aqua>"
  prevButton: "<hover:show_text:'上一页'><dark_aqua> <- </dark_aqua></hover>"
  nextButton: "<hover:show_text:'下一页'><dark_aqua> -> </dark_aqua></hover>"
  item: "<gray>⬡</gray> <white>{num}. <green>{playerName} <grey>-</grey> {count}</green></white>"

lists:
  time:
    color: "#FF0000"
    type: PLAY_ONE_MINUTE

  block:
    color: "#FFA500"
    type: MINE_BLOCK
    material: [solid]

  entity:
    color: "#FF00FF"
    type: KILL_ENTITY
    entity: [all]

