# 每一页上应该有多少玩家
page-size: 10

# 排行榜更新间隔(单位为秒)(不小于30)
update-interval: 60

# 自定义UI部分
ui:
  header: "<aqua>================ <hover:show_text:'<yellow>更新时间: <#FFA500>{updateTime}</#FFA500></yellow>'>{listName} ================</aqua>"
  footer: "<aqua>{prevButton}当前: (<white>{currentIndex}</white>/<white>{totalIndex}</white>){nextButton}</aqua>"
  prev-button: "<hover:show_text:'上一页'><dark_aqua> <- </dark_aqua></hover>"
  next-button: "<hover:show_text:'下一页'><dark_aqua> -> </dark_aqua></hover>"
  item: "<gray>⬡</gray> <white>{num}. <green>{playerName} <grey>-</grey> {count}</green></white>"

# 排行榜部分
lists:
  #示例:
  #这个是排行榜名称
  挖掘榜-总榜:
    # (可选) 这个是排行榜显示颜色
    color: "#FFA500"

    # (必填) 这个是统计数据类型, 可用值见附录1
    type: MINE_BLOCK

    # (选择性必填) 当类型为Statistic.Type.BLOCK或者Statistic.Type.ITEM时必填
    # 除了材料名称外可用值: all, items, blocks, solid
    # 可用值见附录2
    # 注意!!!该项为列表类型
    material: [solid]

    # (选择性必填) 当类型为Statistic.Type.ENTITY时必填
    # 除了实体名称外可用值: all, alive
    # 可用值见附录3
    # 注意!!!该项为列表类型
    entity: [all]

    # (选填) 数值表达式:
    # 用于修正排行榜数值
    expression: "count / 64"

    # (WIP) (选填) 数字格式:
    # java格式化字符串
    formatter: "%.1f 组"

  在线时间:
    color: "#FF0000"
    type: PLAY_ONE_MINUTE
    expression: "count / 20 / 60 / 60"
    formatter: "%.1f 小时"

  挖掘榜-石头:
    color: "#EEEEEE"
    type: MINE_BLOCK
    material: [STONE]

  击杀榜-生物:
    color: "#FF00FF"
    type: KILL_ENTITY
    entity: [alive]

  击杀榜-玩家:
    color: "#FF0022"
    type: KILL_ENTITY
    entity: [PLAYER]

# 附录
# 1.可用统计类型见: https://bukkit.windit.net/javadoc/org/bukkit/Statistic.html
# 2.可用材料类型见: https://bukkit.windit.net/javadoc/org/bukkit/Material.html
# 3.可用实体类型见: https://bukkit.windit.net/javadoc/org/bukkit/entity/EntityType.html