name: PlayerTopList
version: '1.3.0'
main: cn.JvavRE.playerTopList.PlayerTopList
api-version: '1.21'
folia-supported: true
author: Jvav_Runtime_Environment
description: 排行榜插件

softdepend:
  - PlaceholderAPI
  - Vault

commands:
  playertoplist:
    aliases: [ptl]
    description: CrossBank main command
    usage: /<command> [args]

permissions:
  playertoplist.admin:
    default: op
    description: Allows access to admin commands
  playertoplist.view:
    default: true
    description: Allows access to see the top list
